step0_repl: step0/step0_repl.go
	cd step0; go build; cp step0 ../step0_repl

step1_read_print: step1/step1_read_print.go reader.go
	cd step1; go build; cp step1 ../step1_read_print

step2_eval: step2/step2_eval.go reader.go
	cd step2; go build; cp step2 ../step2_eval
